---
all:
  children:
    apic:
      hosts:
        production_apic:
          aci_host: apic.production.example.com
          aci_environment: production
          aci_model_file: '{{ playbook_dir }}/../config/production.yml'
