---
all:
  children:
    apic:
      hosts:
        lab_apic:
          aci_host: apic.lab.example.com
          aci_environment: lab
          aci_model_file: '{{ playbook_dir }}/../examples/full-stack.yml'
